### PR TITLE
Add placeholder image

### PR DESCRIPTION
**Pull request by spencercheng**
related to #112

### CODE REVIEW

**Comment by WorldsEndless** [comment]
Please make the address to the image  a relative (local) address. I think you can replace cam.*.byu.edu with `/`, for example

**Comment by WorldsEndless** [comment]
also, you don't want to link to the upload directory. Put a copy of the right image in the theme itself.

**Comment by spencercheng** [comment]
> also, you don't want to link to the upload directory. Put a copy of the right image in the theme itself.
What do you mean in the theme?

**Comment by spencercheng** [comment]
ah, you mean to code-- 
image
I tried this but whenever I copy the path it doesn't show

**Pull request merged**
